export const ROUTES = {
  home:           '/',
  login:          '/login',
  register:       '/register',
  dashboard:      '/dashboard',
  games:          '/games',
  game:           (id: string) => `/games/${id}`,
  friends:        '/friends',
  profile:        (id: string) => `/profile/${id}`,
  lobby:          (id: string) => `/lobby/${id}`,
  room:           (id: string) => `/room/${id}`,
  leaderboards:   '/leaderboards',
  settings:       '/settings',
  verifyEmail:    '/verify-email',
  verifyConfirm:  '/verify-email/confirm',
  resetPassword:  '/reset-password',
} as const;
